blank_issues_enabled: true
contact_links:
  - name: Genji Ball Ranked Discord
    url: https://discord.gg/sv9VVjh5pT
    about: For questions about ranked and hosting ranked lobbies with the host tool.
